### ISSUE TITLE
Can´t compile

### ISSUE THREAD

**Issue by hyp3rx** [koffienl/ESPimaticRF#1]
Hello,
got:

exit status 1
'send_udp' was not declared in this scope

So can´t compile it !

**Comment by koffienl** [comment]
What version of Arduino IDE and ESP8266 core for arduino are you using?

**Comment by hyp3rx** [comment]
It was the wrong IDE Version. Now with 1.6.5 compiling works. But having now other problems inside pimatic. 

error [pimatic]: Could not initialize the plugin "homeduino": receiverPin must be 0 or 1

What could be wrong ?

**Comment by koffienl** [comment]
The homeduino plugin (on the pimatic side) can't handle all the pin numberings used on the ESP side. Therefore these pin numbers in the plugin config are ignored on the ESP.
Just provide some default pin numbers on the pimatic side:

```
{
  "plugin": "homeduino",
  "driver": "serialport",
  "driverOptions": {
    "serialDevice": "/dev/ttyUSB0",
    "baudrate": 115200
  },
  "receiverPin": 0,
  "transmitterPin": 4,
  "dstSearchAddressPin": 12
}
```

You can enter the actual pin numbers in the config on the ESPimaticRF side : https://github.com/koffienl/ESPimaticRF/wiki/Installing-ESPimaticRF#configuring-the-homeduino

**Comment by hyp3rx** [comment]
This is my config:

```
{
  "plugin": "homeduino",
  "driver": "serialport",
  "debug": true,
  "active": true,
  "driverOptions": {
    "serialDevice": "/dev/ttyUSB3",
    "baudrate": 115200
  },
  "receiverPin": 4,
  "transmitterPin": 5,
  "rfrepeats": 7,
  "enableReceiving": true,
  "apikey": "240282"
},
```

Still the same !

_edit_ Understand .... it must be "0"
will retest now !

**Comment by koffienl** [comment]
You are using pin numbers that the pimatic-homeduino plugin can't handle : https://pimatic.org/plugins/pimatic-homeduino/
Change it to:

```
 "receiverPin": 0,
  "transmitterPin": 4,
```

**Comment by koffienl** [comment]
Added to the wiki : https://github.com/koffienl/ESPimaticRF/wiki/Problems-&-Errors#im-getting-a-error-on-starting-the-pimatic-homeduino-plugin
