### ISSUE TITLE
TimeoutError: operation timed out

### ISSUE THREAD

**Issue by hyp3rx** [koffienl/ESPimaticRF#2]
Hello,
after having trouble moving from older homeduino (arduino) now to ESPimaticRF, the problems are back.

23:22:13error [pimatic-homeduino]: [TimeoutError: operation timed out]
23:22:13error [pimatic-homeduino]: TimeoutError: operation timed out
    at afterTimeout (/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/bluebird/js/main/timers.js:11:15)
    at null.timeoutTimeout (/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/bluebird/js/main/timers.js:53:9)
    at Timer.listOnTimeout (timers.js:92:15)
23:22:13error [pimatic-homeduino]: Couldn't connect to homeduino device: operation timed out.

Still i can receive RF-signals frome node ! At the moment i still don´t know what i can do now because homeduino itself can be reached without any problems. 
I have an idea why:
I have another USB to Serial device and this could conflict with the homeduino itself

in /dev/serial/by-id/ 
The homeduino device is NOT listend ! But it is attached on ttyUSB3 !

Here the list of all devices.

lsusb
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp.
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp.
Bus 001 Device 004: ID 10c4:ea60 Cygnal Integrated Products, Inc. CP210x UART Bridge / myAVR mySmartUSB light
Bus 001 Device 005: ID 10c4:ea60 Cygnal Integrated Products, Inc. CP210x UART Bridge / myAVR mySmartUSB light
**Bus 001 Device 006: ID 1a86:7523 QinHeng Electronics HL-340 USB-Serial adapter**
Bus 001 Device 007: ID 1a40:0101 Terminus Technology Inc. 4-Port HUB
Bus 001 Device 008: ID 1bcf:0c31 Sunplus Innovation Technology Inc. SPIF30x Serial-ATA bridge
**Bus 001 Device 009: ID 1a86:7523 QinHeng Electronics HL-340 USB-Serial adapter**

Strange that both devices got exactly the SAME ID !?
Any ideas?

**Comment by leader21** [comment]
try the serial/by-path method. the same ids result from the ch340 chipset. this cannot differ the ids, other then the ftdi chip. 
having a similar issue with a selfmade cul and a wemos device. both have the same id so i use the by-path method

**Comment by hyp3rx** [comment]
You made my day. To easy... !! Thanks !
You can close the issue
